/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.panel.menu;

import java.util.ArrayList;

/**
 *
 * @author WINDNCC
 */
public class JPanelSubMenu extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSubMenu
     */
    ArrayList<JPanelSubMenuItem> listSubMenuItem;
    public JPanelSubMenu(ArrayList<JPanelSubMenuItem> listSubMenuItem) {
        initComponents();
        this.listSubMenuItem = listSubMenuItem;
        this.listSubMenuItem.forEach((item)->{
            this.add(item);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(34, 45, 68));
        setPreferredSize(null);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
