/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.panel.menu;

import assets.images.icons.IconResources;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JFrame;

/**
 *
 * @author WINDNCC
 */
public class JPanelMenu extends javax.swing.JPanel {

    /**
     * Creates new form JPanelMenu  
     */
    public JPanelMenu() {
        initComponents();
        try{
            JPanelMenuItem menuItemPackage = MenuItemFactory.get("package");
            JPanelMenuItem menuItemOrder = MenuItemFactory.get("order");
            JPanelMenuItem menuItemCoins = MenuItemFactory.get("coins");
            JPanelMenuItem menuItemReport = MenuItemFactory.get("report");
            JPanelMenuItem menuItemStaff = MenuItemFactory.get("staff");
            jPanelMenuContent.add(menuItemOrder);
            jPanelMenuContent.add(menuItemPackage);
            jPanelMenuContent.add(menuItemCoins);
            jPanelMenuContent.add(menuItemReport);
            jPanelMenuContent.add(menuItemStaff);
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenuContent = new javax.swing.JPanel();

        setBackground(new java.awt.Color(70, 92, 139));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanelMenuContent.setLayout(new javax.swing.BoxLayout(jPanelMenuContent, javax.swing.BoxLayout.Y_AXIS));
        add(jPanelMenuContent);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        JFrame jf = new JFrame();
        jf.setSize(new Dimension(500,500));
        JPanelMenu jpm = new JPanelMenu();
        jf.add(jpm);
        jf.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelMenuContent;
    // End of variables declaration//GEN-END:variables
}
