/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.panel.partner;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modal.MProvider;
import modal.MStaff;
import restaurant.panel.staff.JPanelManagementStaff;

/**
 *
 * @author khanhnguyen
 */
public class JPanelSupplierRowItem extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSupplierRowItem
     */
    protected int maNCC;
    protected String tenNCC;
    protected String soDienThoai;
    protected String diaChi;
    protected static Color oddBackground = new Color(224, 224, 235);
    
    public JPanelSupplierRowItem() {
        initComponents();
    }

     public JPanelSupplierRowItem(int supplierID, String supplierName, String phonenumber, String address, boolean odd) {
        initComponents();
        this.maNCC = supplierID;
        this.tenNCC = supplierName;
        this.soDienThoai = phonenumber;
        this.diaChi = address;
        
        if(odd){
            setBackground(oddBackground);
        }
        customInit();
    }
     
     public void customInit(){
        jLabelStaffId.setText(this.maNCC + "");
        jLabelSupplierName.setText("<html><p>" + this.tenNCC + "</p></html>");
        jLabelSupplierPhoneNumber.setText(this.soDienThoai + " ");
        jLabelSupplierAddress.setText(this.diaChi + " ");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStaffId = new javax.swing.JLabel();
        jLabelSupplierName = new javax.swing.JLabel();
        jLabelSupplierPhoneNumber = new javax.swing.JLabel();
        jLabelEdit = new javax.swing.JLabel();
        jLabelDelete = new javax.swing.JLabel();
        jLabelSupplierAddress = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(760, 57));
        setMinimumSize(new java.awt.Dimension(760, 57));
        setPreferredSize(new java.awt.Dimension(760, 57));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStaffId.setText("001");
        add(jLabelStaffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 69, 60));

        jLabelSupplierName.setText("tên ncc");
        add(jLabelSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 0, 167, 60));

        jLabelSupplierPhoneNumber.setText("sđt");
        add(jLabelSupplierPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 0, 121, 60));

        jLabelEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/icon_edit_darkgreen_x24.png"))); // NOI18N
        jLabelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditMouseClicked(evt);
            }
        });
        add(jLabelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 11, 32, 32));

        jLabelDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/icon_delete_dimgray_x32.png"))); // NOI18N
        jLabelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDeleteMouseClicked(evt);
            }
        });
        add(jLabelDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 11, -1, -1));

        jLabelSupplierAddress.setText("address");
        add(jLabelSupplierAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 0, 235, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEditMouseClicked

    private void jLabelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteMouseClicked
        int check = JOptionPane.showConfirmDialog(JPanelManagementSupplier.getInstance(), "Xác nhận xóa?");
        if (check == JOptionPane.YES_OPTION) {
            try {
                MProvider mProvider = new MProvider(maNCC);
                mProvider.delete();
                JPanelManagementSupplier.getInstance().getjPanelTableContent().remove(this);
                JPanelManagementSupplier.getInstance().getjPanelTableContent().revalidate();
                JPanelManagementSupplier.getInstance().getjPanelTableContent().repaint();
            } catch (SQLException e) {
            }
        }
      
    }//GEN-LAST:event_jLabelDeleteMouseClicked

    public JLabel getjLabelDelete() {
        return jLabelDelete;
    }

    public JLabel getjLabelEdit() {
        return jLabelEdit;
    }

    
    public int getMaNCC() {
        return maNCC;
    }

    public void setMaNCC(int maNCC) {
        this.maNCC = maNCC;
    }

    public String getTenNCC() {
        return tenNCC;
    }

    public void setTenNCC(String tenNCC) {
        this.tenNCC = tenNCC;
    }

    public String getSoDienThoai() {
        return soDienThoai;
    }

    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    
    public void setDiaChi(String diaChi){
        this.diaChi = diaChi;
    }

    public static Color getOddBackground() {
        return oddBackground;
    }

    public static void setOddBackground(Color oddBackground) {
        JPanelSupplierRowItem.oddBackground = oddBackground;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDelete;
    private javax.swing.JLabel jLabelEdit;
    private javax.swing.JLabel jLabelStaffId;
    private javax.swing.JLabel jLabelSupplierAddress;
    private javax.swing.JLabel jLabelSupplierName;
    private javax.swing.JLabel jLabelSupplierPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
