/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.panel.partner;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JLabel;
import modal.MCustomer;
import modal.MStaff;

/**
 *
 * @author khanhnguyen
 */
public class JPanelCustomerRowItem extends javax.swing.JPanel {

    protected int maKH;
    protected String tenKH;
    protected String soDienThoai;
    protected String diaChi;
    protected static Color oddBackground = new Color(224, 224, 235);
    public JPanelCustomerRowItem() {
        initComponents();
    }
    public JPanelCustomerRowItem(int customerID, String customerName, String phonenumber, String address, boolean odd) {
        initComponents();
        this.maKH = customerID;
        this.tenKH = customerName;
        this.soDienThoai = phonenumber;
        this.diaChi = address;
        
        if(odd){
            setBackground(oddBackground);
        }
        customInit();
    }
    public void customInit(){
        jLabelStaffId.setText(this.maKH + "");
        jLabelCustomerName.setText("<html><p>" + this.tenKH + "</p></html>");
        jLabelCustomerPhoneNumber.setText(this.soDienThoai + " ");
        jLabelCustomerAddress.setText(this.diaChi + " ");
    }
    /**
     * Creates new form JPanelCustomerRowItem
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStaffId = new javax.swing.JLabel();
        jLabelCustomerName = new javax.swing.JLabel();
        jLabelCustomerPhoneNumber = new javax.swing.JLabel();
        jLabelEdit = new javax.swing.JLabel();
        jLabelDelete = new javax.swing.JLabel();
        jLabelCustomerAddress = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(760, 57));
        setMinimumSize(new java.awt.Dimension(760, 57));
        setPreferredSize(new java.awt.Dimension(760, 57));

        jLabelStaffId.setText("001");

        jLabelCustomerName.setText("Thịt xông khói");

        jLabelCustomerPhoneNumber.setText("120000000");

        jLabelEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/icon_edit_green_x24.png"))); // NOI18N
        jLabelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEditMouseClicked(evt);
            }
        });

        jLabelDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/icons/icon_dell_gray_x24.png"))); // NOI18N
        jLabelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDeleteMouseClicked(evt);
            }
        });

        jLabelCustomerAddress.setText("limit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabelCustomerPhoneNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jLabelCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEdit)
                .addGap(18, 18, 18)
                .addComponent(jLabelDelete)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDelete)
                    .addComponent(jLabelEdit))
                .addGap(17, 17, 17))
            .addComponent(jLabelCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelCustomerPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelCustomerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelStaffId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEditMouseClicked

    private void jLabelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeleteMouseClicked
        // TODO add your handling code here:
        //       MStaff mStaff = new MStaff(tenNV, soDienThoai , diaChi);
        //       mStaff.delete();

        try {
            MCustomer mCustomer = new MCustomer(maKH);
            mCustomer.delete();
            JPanelManagementCustomer.getInstance().getjPanelTableContent().remove(this);
            JPanelManagementCustomer.getInstance().getjPanelTableContent().revalidate();
            JPanelManagementCustomer.getInstance().getjPanelTableContent().repaint();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jLabelDeleteMouseClicked

    public JLabel getjLabelDelete() {
        return jLabelDelete;
    }

    public JLabel getjLabelEdit() {
        return jLabelEdit;
    }

     public int getMaKH() {
        return maKH;
    }

    public void setMaKH(int maKH) {
        this.maKH = maKH;
    }

    public String getTenKH() {
        return tenKH;
    }

    public void setTenKH(String tenKH) {
        this.tenKH = tenKH;
    }

    public String getSoDienThoai() {
        return soDienThoai;
    }

    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    
    public void setDiaChi(String diaChi){
        this.diaChi = diaChi;
    }

    public static Color getOddBackground() {
        return oddBackground;
    }

    public static void setOddBackground(Color oddBackground) {
        JPanelCustomerRowItem.oddBackground = oddBackground;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCustomerAddress;
    private javax.swing.JLabel jLabelCustomerName;
    private javax.swing.JLabel jLabelCustomerPhoneNumber;
    private javax.swing.JLabel jLabelDelete;
    private javax.swing.JLabel jLabelEdit;
    private javax.swing.JLabel jLabelStaffId;
    // End of variables declaration//GEN-END:variables
}
